FROM pgvector/pgvector:pg16

# 초기화 스크립트 복사
COPY ./init-db.sh /docker-entrypoint-initdb.d/

# 권한 설정
RUN chmod +x /docker-entrypoint-initdb.d/init-db.sh

# 환경변수 설정
ENV POSTGRES_DB=postgres
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres

# 포트 노출
EXPOSE 5432
